spring:
  application:
    name: nexus-boot
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET}

employee:
  auth-service:
    base-url: ${AUTH_SERVICE_BASE_URL}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    try-it-out-enabled: true
    operations-sorter: alpha
    tags-sorter: alpha